name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: npm run client-prod
        run: npm run client-prod

      - name: rm -rf ./web/client/dist/.gitignore
        run: rm -rf ./web/client/dist/.gitignore

      - name: deploy github pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/client/dist/